services:
  jenkins:
    image: jenkins/jenkins:lts
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    ports: 
      - 9000:8080
      - 50000:50000
    privileged: true
    user: root
    restart: always
    container_name: jenkins
    environment:
      TZ: Asia/Shanghai